# Generated by Django 5.1.4 on 2024-12-13 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 12, 13, 20, 35, 32, 490331))),
            ],
        ),
    ]
